/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.awt.Color;

/**
 *
 * @author jesus
 */
public class agregarUsuario extends javax.swing.JPanel {

    public boolean carga = false;
    
    public agregarUsuario() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCorreoUsuario = new design.TextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombrePersona = new design.TextField();
        jLabel6 = new javax.swing.JLabel();
        comboTipoUsuario = new design.Combobox();
        btnAcceptPanel = new javax.swing.JPanel();
        btnAcceptLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombreUsuario = new design.TextField();
        txtClaveUsuario = new javax.swing.JPasswordField();
        txtConfirmarClave = new javax.swing.JLabel();
        txtConfirmarClaveUsuario = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAppPersona = new design.TextField();
        jLabel10 = new javax.swing.JLabel();
        txtApmPersona = new design.TextField();
        calendarFechaPersona = new com.toedter.calendar.JCalendar();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1588, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Usuario");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 35, -1, -1));

        txtCorreoUsuario.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtCorreoUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreoUsuario.setBorder(null);
        txtCorreoUsuario.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtCorreoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCorreoUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCorreoUsuarioMouseExited(evt);
            }
        });
        txtCorreoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoUsuarioActionPerformed(evt);
            }
        });
        add(txtCorreoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 450, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setText("Correo");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar-archivo.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 83));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setText("Clave");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setText("Fecha nacimiento");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        txtNombrePersona.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtNombrePersona.setForeground(new java.awt.Color(153, 153, 153));
        txtNombrePersona.setBorder(null);
        txtNombrePersona.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtNombrePersona.setMaximumSize(new java.awt.Dimension(1920, 1080));
        txtNombrePersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombrePersonaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNombrePersonaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNombrePersonaMouseExited(evt);
            }
        });
        txtNombrePersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePersonaActionPerformed(evt);
            }
        });
        add(txtNombrePersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 454, 30));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setText("Tipo");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 120, -1, -1));

        comboTipoUsuario.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        comboTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 150, 450, 35));

        btnAcceptPanel.setBackground(new java.awt.Color(249, 204, 15));
        btnAcceptPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcceptPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAcceptPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcceptPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcceptPanelMouseExited(evt);
            }
        });
        btnAcceptPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAcceptLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnAcceptLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAcceptLabel.setText("AGREGAR");
        btnAcceptLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcceptLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAcceptLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcceptLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcceptLabelMouseExited(evt);
            }
        });
        btnAcceptPanel.add(btnAcceptLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 10, 1560, -1));

        add(btnAcceptPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, 1570, 40));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel7.setText("Datos personales");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        txtNombreUsuario.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtNombreUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreUsuario.setBorder(null);
        txtNombreUsuario.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtNombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNombreUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNombreUsuarioMouseExited(evt);
            }
        });
        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });
        add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 450, 30));

        txtClaveUsuario.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtClaveUsuario.setForeground(new java.awt.Color(153, 153, 153));
        add(txtClaveUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 450, 30));

        txtConfirmarClave.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtConfirmarClave.setText("Confirmar clave");
        add(txtConfirmarClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, -1, -1));

        txtConfirmarClaveUsuario.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtConfirmarClaveUsuario.setForeground(new java.awt.Color(153, 153, 153));
        add(txtConfirmarClaveUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 450, 30));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel8.setText("Nombre de usuario");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel9.setText("Apellido paterno");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, -1, -1));

        txtAppPersona.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtAppPersona.setForeground(new java.awt.Color(153, 153, 153));
        txtAppPersona.setBorder(null);
        txtAppPersona.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtAppPersona.setMaximumSize(new java.awt.Dimension(1920, 1080));
        txtAppPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAppPersonaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAppPersonaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAppPersonaMouseExited(evt);
            }
        });
        txtAppPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAppPersonaActionPerformed(evt);
            }
        });
        add(txtAppPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 454, 30));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel10.setText("Apellido materno");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 370, -1, -1));

        txtApmPersona.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtApmPersona.setForeground(new java.awt.Color(153, 153, 153));
        txtApmPersona.setBorder(null);
        txtApmPersona.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtApmPersona.setMaximumSize(new java.awt.Dimension(1920, 1080));
        txtApmPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApmPersonaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtApmPersonaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtApmPersonaMouseExited(evt);
            }
        });
        txtApmPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApmPersonaActionPerformed(evt);
            }
        });
        add(txtApmPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 400, 454, 30));
        add(calendarFechaPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel11.setText("Nombre");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoUsuarioMouseClicked

    }//GEN-LAST:event_txtCorreoUsuarioMouseClicked

    private void txtCorreoUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoUsuarioMouseEntered

    }//GEN-LAST:event_txtCorreoUsuarioMouseEntered

    private void txtCorreoUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoUsuarioMouseExited

    }//GEN-LAST:event_txtCorreoUsuarioMouseExited

    private void txtCorreoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoUsuarioActionPerformed

    }//GEN-LAST:event_txtCorreoUsuarioActionPerformed

    private void txtNombrePersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombrePersonaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePersonaMouseClicked

    private void txtNombrePersonaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombrePersonaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePersonaMouseEntered

    private void txtNombrePersonaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombrePersonaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePersonaMouseExited

    private void txtNombrePersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePersonaActionPerformed

    private void btnAcceptPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPanelMouseClicked

    }//GEN-LAST:event_btnAcceptPanelMouseClicked

    private void btnAcceptPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPanelMouseEntered
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(18,5,58));
            btnAcceptLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnAcceptPanelMouseEntered

    private void btnAcceptPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPanelMouseExited
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(249,204,15));
            btnAcceptLabel.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_btnAcceptPanelMouseExited

    private void btnAcceptLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptLabelMouseEntered
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(18,5,58));
            btnAcceptLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnAcceptLabelMouseEntered

    private void btnAcceptLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptLabelMouseExited
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(249,204,15));
            btnAcceptLabel.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_btnAcceptLabelMouseExited

    private void txtNombreUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreUsuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioMouseClicked

    private void txtNombreUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreUsuarioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioMouseEntered

    private void txtNombreUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreUsuarioMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioMouseExited

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void txtAppPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAppPersonaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppPersonaMouseClicked

    private void txtAppPersonaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAppPersonaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppPersonaMouseEntered

    private void txtAppPersonaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAppPersonaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppPersonaMouseExited

    private void txtAppPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAppPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppPersonaActionPerformed

    private void txtApmPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApmPersonaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApmPersonaMouseClicked

    private void txtApmPersonaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApmPersonaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApmPersonaMouseEntered

    private void txtApmPersonaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApmPersonaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApmPersonaMouseExited

    private void txtApmPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApmPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApmPersonaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnAcceptLabel;
    public javax.swing.JPanel btnAcceptPanel;
    public com.toedter.calendar.JCalendar calendarFechaPersona;
    public javax.swing.JComboBox<String> comboTipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField txtApmPersona;
    public javax.swing.JTextField txtAppPersona;
    public javax.swing.JPasswordField txtClaveUsuario;
    private javax.swing.JLabel txtConfirmarClave;
    private javax.swing.JPasswordField txtConfirmarClaveUsuario;
    public javax.swing.JTextField txtCorreoUsuario;
    public javax.swing.JTextField txtNombrePersona;
    public javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
