/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.awt.Color;

/**
 *
 * @author jesus
 */
public class agregarMarca extends javax.swing.JPanel {

    public boolean carga = false;
    
    public agregarMarca() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAcceptPanel = new javax.swing.JPanel();
        btnAcceptLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombreMarca = new design.TextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1588, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Marca");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 35, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar-archivo.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 83));

        btnAcceptPanel.setBackground(new java.awt.Color(249, 204, 15));
        btnAcceptPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcceptPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAcceptPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcceptPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcceptPanelMouseExited(evt);
            }
        });
        btnAcceptPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAcceptLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnAcceptLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAcceptLabel.setText("AGREGAR");
        btnAcceptLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcceptLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAcceptLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcceptLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcceptLabelMouseExited(evt);
            }
        });
        btnAcceptPanel.add(btnAcceptLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 10, 1560, -1));

        add(btnAcceptPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 1570, 40));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setText("Nombre");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txtNombreMarca.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtNombreMarca.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreMarca.setBorder(null);
        txtNombreMarca.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtNombreMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMarcaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNombreMarcaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNombreMarcaMouseExited(evt);
            }
        });
        txtNombreMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreMarcaActionPerformed(evt);
            }
        });
        add(txtNombreMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 450, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPanelMouseClicked

    }//GEN-LAST:event_btnAcceptPanelMouseClicked

    private void btnAcceptPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPanelMouseEntered
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(18,5,58));
            btnAcceptLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnAcceptPanelMouseEntered

    private void btnAcceptPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPanelMouseExited
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(249,204,15));
            btnAcceptLabel.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_btnAcceptPanelMouseExited

    private void btnAcceptLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptLabelMouseEntered
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(18,5,58));
            btnAcceptLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnAcceptLabelMouseEntered

    private void btnAcceptLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptLabelMouseExited
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(249,204,15));
            btnAcceptLabel.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_btnAcceptLabelMouseExited

    private void txtNombreMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMarcaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMarcaMouseClicked

    private void txtNombreMarcaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMarcaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMarcaMouseEntered

    private void txtNombreMarcaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMarcaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMarcaMouseExited

    private void txtNombreMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMarcaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnAcceptLabel;
    public javax.swing.JPanel btnAcceptPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JTextField txtNombreMarca;
    // End of variables declaration//GEN-END:variables
}
