/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

public class dash extends javax.swing.JFrame {
    
    public dash() {
        initComponents();
        panelLoader.setVisible(true);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLoader = new javax.swing.JPanel();
        lbImgLoader = new javax.swing.JLabel();
        lbLoader = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panelButton1 = new javax.swing.JPanel();
        labelButton1 = new javax.swing.JLabel();
        btnVistaVentaPanel = new javax.swing.JPanel();
        btnVistaVentaLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelTipoUsuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        panelButton3 = new javax.swing.JPanel();
        labelButton3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jContent = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelButtonSalir1 = new javax.swing.JPanel();
        labelButtonSalir1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        horaActual = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fechaActual = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLoader.setBackground(new java.awt.Color(255, 255, 255));
        panelLoader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbImgLoader.setBackground(new java.awt.Color(255, 255, 255));
        lbImgLoader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/loader.gif"))); // NOI18N
        panelLoader.add(lbImgLoader, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 200, 180));

        lbLoader.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbLoader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLoader.setText("Cargando...");
        panelLoader.add(lbLoader, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 200, 20));

        getContentPane().add(panelLoader, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 650, 390));

        jPanel4.setBackground(new java.awt.Color(18, 5, 58));
        jPanel4.setPreferredSize(new java.awt.Dimension(330, 553));
        jPanel4.setRequestFocusEnabled(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelButton1.setBackground(new java.awt.Color(249, 204, 15));
        panelButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelButton1MouseExited(evt);
            }
        });
        panelButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelButton1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        labelButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/speedometer.png"))); // NOI18N
        labelButton1.setText("   Dashboard");
        labelButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelButton1MouseExited(evt);
            }
        });
        panelButton1.add(labelButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 290, 40));

        jPanel4.add(panelButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 310, 60));

        btnVistaVentaPanel.setBackground(new java.awt.Color(249, 204, 15));
        btnVistaVentaPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVistaVentaPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVistaVentaPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVistaVentaPanelMouseExited(evt);
            }
        });
        btnVistaVentaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVistaVentaLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnVistaVentaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVistaVentaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito.png"))); // NOI18N
        btnVistaVentaLabel.setText("   Punto de venta");
        btnVistaVentaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVistaVentaLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVistaVentaLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVistaVentaLabelMouseExited(evt);
            }
        });
        btnVistaVentaPanel.add(btnVistaVentaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 290, 38));

        jPanel4.add(btnVistaVentaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 310, 60));

        jPanel1.setBackground(new java.awt.Color(249, 204, 15));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("V.1.0.0");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 180, 80));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BusSoft");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 290, 80));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 80));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 70));

        labelTipoUsuario.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        labelTipoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labelTipoUsuario.setText("Tipo");
        jPanel4.add(labelTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Usuario:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 70, -1));

        labelNombre.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre.setText("Usuario");
        jPanel4.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        panelButton3.setBackground(new java.awt.Color(249, 204, 15));
        panelButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelButton3MouseExited(evt);
            }
        });
        panelButton3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelButton3.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        labelButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/administracion.png"))); // NOI18N
        labelButton3.setText("   Administrador");
        labelButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelButton3MouseExited(evt);
            }
        });
        panelButton3.add(labelButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 290, 38));

        jPanel4.add(panelButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 930, 310, 60));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Copyright © 2022 BusSoft. All Rights Reserved.");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 1050, 240, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 331, 1080));

        jContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jContentLayout = new javax.swing.GroupLayout(jContent);
        jContent.setLayout(jContentLayout);
        jContentLayout.setHorizontalGroup(
            jContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1694, Short.MAX_VALUE)
        );
        jContentLayout.setVerticalGroup(
            jContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        getContentPane().add(jContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 80, -1, 1000));

        jPanel2.setBackground(new java.awt.Color(18, 5, 58));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelButtonSalir1.setBackground(new java.awt.Color(18, 5, 58));
        panelButtonSalir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelButtonSalir1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelButtonSalir1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelButtonSalir1MouseExited(evt);
            }
        });
        panelButtonSalir1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelButtonSalir1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        labelButtonSalir1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelButtonSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-x.png"))); // NOI18N
        labelButtonSalir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelButtonSalir1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelButtonSalir1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelButtonSalir1MouseExited(evt);
            }
        });
        panelButtonSalir1.add(labelButtonSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 80));

        jPanel2.add(panelButtonSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 0, 90, 80));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hora:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        horaActual.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        horaActual.setForeground(new java.awt.Color(255, 255, 255));
        horaActual.setText("00:00");
        jPanel2.add(horaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        fechaActual.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        fechaActual.setForeground(new java.awt.Color(255, 255, 255));
        fechaActual.setText("00/00/0000");
        jPanel2.add(fechaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fecha-limite.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 1590, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void setPanelButtonColor1(javax.swing.JPanel button){
        button.setBackground(new Color(255,255,255));
    }
    
    public void setPanelButtonColor2(javax.swing.JPanel button){
        button.setBackground(new Color(249,204,15));
    }
    
    public void setPanelButtonColor3(javax.swing.JPanel button){
        button.setBackground(new Color(18,5,58));
    }
    
    private void panelButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelButton1MouseEntered
        setPanelButtonColor1(panelButton1);
    }//GEN-LAST:event_panelButton1MouseEntered

    private void panelButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelButton1MouseExited
        setPanelButtonColor2(panelButton1);
    }//GEN-LAST:event_panelButton1MouseExited

    private void labelButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButton1MouseEntered
        setPanelButtonColor1(panelButton1);
    }//GEN-LAST:event_labelButton1MouseEntered

    private void labelButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButton1MouseExited
        setPanelButtonColor2(panelButton1);
    }//GEN-LAST:event_labelButton1MouseExited

    private void btnVistaVentaLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVistaVentaLabelMouseEntered
        setPanelButtonColor1(btnVistaVentaPanel);
    }//GEN-LAST:event_btnVistaVentaLabelMouseEntered

    private void btnVistaVentaLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVistaVentaLabelMouseExited
        setPanelButtonColor2(btnVistaVentaPanel);
    }//GEN-LAST:event_btnVistaVentaLabelMouseExited

    private void btnVistaVentaPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVistaVentaPanelMouseEntered
       setPanelButtonColor1(btnVistaVentaPanel);
    }//GEN-LAST:event_btnVistaVentaPanelMouseEntered

    private void btnVistaVentaPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVistaVentaPanelMouseExited
       setPanelButtonColor2(btnVistaVentaPanel);
    }//GEN-LAST:event_btnVistaVentaPanelMouseExited

    private void labelButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButton3MouseEntered
        setPanelButtonColor1(panelButton3);
    }//GEN-LAST:event_labelButton3MouseEntered

    private void labelButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButton3MouseExited
        setPanelButtonColor2(panelButton3);
    }//GEN-LAST:event_labelButton3MouseExited

    private void panelButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelButton3MouseEntered
        setPanelButtonColor1(panelButton3);
    }//GEN-LAST:event_panelButton3MouseEntered

    private void panelButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelButton3MouseExited
        setPanelButtonColor2(panelButton3);
    }//GEN-LAST:event_panelButton3MouseExited

    private void labelButtonSalir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonSalir1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_labelButtonSalir1MouseClicked
    
    private void labelButton1MouseClicked(java.awt.event.MouseEvent evt) {                                               
    }
    
    private void btnVistaVentaPanelMouseClicked(java.awt.event.MouseEvent evt) {                                               
    }
    
    private void btnVistaVentaLabelMouseClicked(java.awt.event.MouseEvent evt) {                                               
    }
    
    private void labelButton2MouseClicked(java.awt.event.MouseEvent evt) {                                               
    }
    
    private void labelButton3MouseClicked(java.awt.event.MouseEvent evt) {                                               
    }
    
    private void panelButton1MouseClicked(java.awt.event.MouseEvent evt) {                                               
    }
    
    private void panelButton2MouseClicked(java.awt.event.MouseEvent evt) {                                               
    }
    
    private void panelButton3MouseClicked(java.awt.event.MouseEvent evt) {                                               
    }    
     
    private void labelButtonSalir1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonSalir1MouseEntered
        //panelButtonSalir1.setBackground(new Color(255,102,102));
    }//GEN-LAST:event_labelButtonSalir1MouseEntered

    private void labelButtonSalir1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonSalir1MouseExited
        //panelButtonSalir1.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_labelButtonSalir1MouseExited

    private void panelButtonSalir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelButtonSalir1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_panelButtonSalir1MouseClicked

    private void panelButtonSalir1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelButtonSalir1MouseEntered
        //panelButtonSalir1.setBackground(new Color(255,102,102));
    }//GEN-LAST:event_panelButtonSalir1MouseEntered

    private void panelButtonSalir1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelButtonSalir1MouseExited
        //panelButtonSalir1.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_panelButtonSalir1MouseExited
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnVistaVentaLabel;
    public javax.swing.JPanel btnVistaVentaPanel;
    public javax.swing.JLabel fechaActual;
    public javax.swing.JLabel horaActual;
    public javax.swing.JPanel jContent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JLabel labelButton1;
    public javax.swing.JLabel labelButton3;
    private javax.swing.JLabel labelButtonSalir1;
    public javax.swing.JLabel labelNombre;
    public javax.swing.JLabel labelTipoUsuario;
    public javax.swing.JLabel lbImgLoader;
    private javax.swing.JLabel lbLoader;
    public javax.swing.JPanel panelButton1;
    public javax.swing.JPanel panelButton3;
    private javax.swing.JPanel panelButtonSalir1;
    public javax.swing.JPanel panelLoader;
    // End of variables declaration//GEN-END:variables
}
