/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.awt.Color;
import controlador.*;

/**
 *
 * @author jesus
 */
public class menuAdmin extends javax.swing.JPanel {

    dash dash;

    public menuAdmin() {
        initComponents();
        dash = new dash();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelButtonProductoAgregar = new javax.swing.JPanel();
        labelButtonProductoAgregar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelButtonProductoVer = new javax.swing.JPanel();
        labelButtonProductoVer = new javax.swing.JLabel();
        panelButtonProductomModificar = new javax.swing.JPanel();
        labelButtonProductoModificar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAddMPanel = new javax.swing.JPanel();
        btnAddMLabel = new javax.swing.JLabel();
        btnVerMPanel = new javax.swing.JPanel();
        btnVerMLabel = new javax.swing.JLabel();
        btnModMPanel = new javax.swing.JPanel();
        btnModMLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAddUserPanel = new javax.swing.JPanel();
        btnAddUserLabel = new javax.swing.JLabel();
        btnVerUserPanel = new javax.swing.JPanel();
        btnVerUserLabel = new javax.swing.JLabel();
        btnModUserPanel = new javax.swing.JPanel();
        btnModUserLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1588, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("Menu Administrador");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 35, -1, -1));

        panelButtonProductoAgregar.setBackground(new java.awt.Color(249, 204, 15));
        panelButtonProductoAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelButtonProductoAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelButtonProductoAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelButtonProductoAgregarMouseExited(evt);
            }
        });
        panelButtonProductoAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelButtonProductoAgregar.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        labelButtonProductoAgregar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelButtonProductoAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar-archivo.png"))); // NOI18N
        labelButtonProductoAgregar.setText("   Agregar");
        labelButtonProductoAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelButtonProductoAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelButtonProductoAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelButtonProductoAgregarMouseExited(evt);
            }
        });
        panelButtonProductoAgregar.add(labelButtonProductoAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 290, -1));

        add(panelButtonProductoAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 310, 84));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel2.setText("Marcas");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/administracion.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 62));

        panelButtonProductoVer.setBackground(new java.awt.Color(249, 204, 15));
        panelButtonProductoVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelButtonProductoVerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelButtonProductoVerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelButtonProductoVerMouseExited(evt);
            }
        });
        panelButtonProductoVer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelButtonProductoVer.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        labelButtonProductoVer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelButtonProductoVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ojo.png"))); // NOI18N
        labelButtonProductoVer.setText("   Ver");
        labelButtonProductoVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelButtonProductoVerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelButtonProductoVerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelButtonProductoVerMouseExited(evt);
            }
        });
        panelButtonProductoVer.add(labelButtonProductoVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 290, -1));

        add(panelButtonProductoVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 310, 84));

        panelButtonProductomModificar.setBackground(new java.awt.Color(249, 204, 15));
        panelButtonProductomModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelButtonProductomModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelButtonProductomModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelButtonProductomModificarMouseExited(evt);
            }
        });
        panelButtonProductomModificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelButtonProductoModificar.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        labelButtonProductoModificar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelButtonProductoModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        labelButtonProductoModificar.setText("   Modificar");
        labelButtonProductoModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelButtonProductoModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelButtonProductoModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelButtonProductoModificarMouseExited(evt);
            }
        });
        panelButtonProductomModificar.add(labelButtonProductoModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 290, -1));

        add(panelButtonProductomModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, -1, 84));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel4.setText("Productos");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        btnAddMPanel.setBackground(new java.awt.Color(249, 204, 15));
        btnAddMPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMPanelMouseExited(evt);
            }
        });
        btnAddMPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddMLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnAddMLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddMLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar-archivo.png"))); // NOI18N
        btnAddMLabel.setText("   Agregar");
        btnAddMLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMLabelMouseExited(evt);
            }
        });
        btnAddMPanel.add(btnAddMLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 290, -1));

        add(btnAddMPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 310, 84));

        btnVerMPanel.setBackground(new java.awt.Color(249, 204, 15));
        btnVerMPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerMPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerMPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerMPanelMouseExited(evt);
            }
        });
        btnVerMPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVerMLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnVerMLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVerMLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ojo.png"))); // NOI18N
        btnVerMLabel.setText("   Ver");
        btnVerMLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerMLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerMLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerMLabelMouseExited(evt);
            }
        });
        btnVerMPanel.add(btnVerMLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 290, -1));

        add(btnVerMPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 310, 84));

        btnModMPanel.setBackground(new java.awt.Color(249, 204, 15));
        btnModMPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModMPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModMPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModMPanelMouseExited(evt);
            }
        });
        btnModMPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModMLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnModMLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnModMLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btnModMLabel.setText("   Modificar");
        btnModMLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModMLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModMLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModMLabelMouseExited(evt);
            }
        });
        btnModMPanel.add(btnModMLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 290, -1));

        add(btnModMPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, -1, 84));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel5.setText("Usuarios");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        btnAddUserPanel.setBackground(new java.awt.Color(249, 204, 15));
        btnAddUserPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddUserPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddUserPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddUserPanelMouseExited(evt);
            }
        });
        btnAddUserPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddUserLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnAddUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddUserLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar-archivo.png"))); // NOI18N
        btnAddUserLabel.setText("   Agregar");
        btnAddUserLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddUserLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddUserLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddUserLabelMouseExited(evt);
            }
        });
        btnAddUserPanel.add(btnAddUserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 290, -1));

        add(btnAddUserPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 310, 84));

        btnVerUserPanel.setBackground(new java.awt.Color(249, 204, 15));
        btnVerUserPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerUserPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerUserPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerUserPanelMouseExited(evt);
            }
        });
        btnVerUserPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVerUserLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnVerUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVerUserLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ojo.png"))); // NOI18N
        btnVerUserLabel.setText("   Ver");
        btnVerUserLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerUserLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerUserLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerUserLabelMouseExited(evt);
            }
        });
        btnVerUserPanel.add(btnVerUserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 290, -1));

        add(btnVerUserPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 310, 84));

        btnModUserPanel.setBackground(new java.awt.Color(249, 204, 15));
        btnModUserPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModUserPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModUserPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModUserPanelMouseExited(evt);
            }
        });
        btnModUserPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModUserLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnModUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnModUserLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btnModUserLabel.setText("   Modificar");
        btnModUserLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModUserLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModUserLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModUserLabelMouseExited(evt);
            }
        });
        btnModUserPanel.add(btnModUserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 290, -1));

        add(btnModUserPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, -1, 84));
    }// </editor-fold>//GEN-END:initComponents

    private void labelButtonProductoAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonProductoAgregarMouseClicked
        dash.setPanelButtonColor2(panelButtonProductoAgregar);
        labelButtonProductoAgregar.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_labelButtonProductoAgregarMouseClicked

    private void labelButtonProductoAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonProductoAgregarMouseEntered
        dash.setPanelButtonColor3(panelButtonProductoAgregar);
        labelButtonProductoAgregar.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_labelButtonProductoAgregarMouseEntered

    private void labelButtonProductoAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonProductoAgregarMouseExited
        dash.setPanelButtonColor2(panelButtonProductoAgregar);
        labelButtonProductoAgregar.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_labelButtonProductoAgregarMouseExited

    private void panelButtonProductoAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelButtonProductoAgregarMouseClicked
        dash.setPanelButtonColor2(panelButtonProductoAgregar);
        labelButtonProductoAgregar.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_panelButtonProductoAgregarMouseClicked

    private void panelButtonProductoAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelButtonProductoAgregarMouseEntered
        dash.setPanelButtonColor3(panelButtonProductoAgregar);
        labelButtonProductoAgregar.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_panelButtonProductoAgregarMouseEntered

    private void panelButtonProductoAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelButtonProductoAgregarMouseExited
        dash.setPanelButtonColor2(panelButtonProductoAgregar);
        labelButtonProductoAgregar.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_panelButtonProductoAgregarMouseExited

    private void labelButtonProductoVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonProductoVerMouseClicked
        dash.setPanelButtonColor2(panelButtonProductoVer);
        labelButtonProductoVer.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_labelButtonProductoVerMouseClicked

    private void labelButtonProductoVerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonProductoVerMouseEntered
        dash.setPanelButtonColor3(panelButtonProductoVer);
        labelButtonProductoVer.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_labelButtonProductoVerMouseEntered

    private void labelButtonProductoVerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonProductoVerMouseExited
        dash.setPanelButtonColor2(panelButtonProductoVer);
        labelButtonProductoVer.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_labelButtonProductoVerMouseExited

    private void panelButtonProductoVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelButtonProductoVerMouseClicked
        dash.setPanelButtonColor2(panelButtonProductoVer);
        labelButtonProductoVer.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_panelButtonProductoVerMouseClicked

    private void panelButtonProductoVerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelButtonProductoVerMouseEntered
        dash.setPanelButtonColor3(panelButtonProductoVer);
        labelButtonProductoVer.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_panelButtonProductoVerMouseEntered

    private void panelButtonProductoVerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelButtonProductoVerMouseExited
        dash.setPanelButtonColor2(panelButtonProductoVer);
        labelButtonProductoVer.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_panelButtonProductoVerMouseExited

    private void labelButtonProductoModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonProductoModificarMouseClicked
        dash.setPanelButtonColor2(panelButtonProductomModificar);
        labelButtonProductoModificar.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_labelButtonProductoModificarMouseClicked

    private void labelButtonProductoModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonProductoModificarMouseEntered
        dash.setPanelButtonColor3(panelButtonProductomModificar);
        labelButtonProductoModificar.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_labelButtonProductoModificarMouseEntered

    private void labelButtonProductoModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonProductoModificarMouseExited
        dash.setPanelButtonColor2(panelButtonProductomModificar);
        labelButtonProductoModificar.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_labelButtonProductoModificarMouseExited

    private void panelButtonProductomModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelButtonProductomModificarMouseClicked
        dash.setPanelButtonColor2(panelButtonProductomModificar);
        labelButtonProductoModificar.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_panelButtonProductomModificarMouseClicked

    private void panelButtonProductomModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelButtonProductomModificarMouseEntered
        dash.setPanelButtonColor3(panelButtonProductomModificar);
        labelButtonProductoModificar.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_panelButtonProductomModificarMouseEntered

    private void panelButtonProductomModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelButtonProductomModificarMouseExited
        dash.setPanelButtonColor2(panelButtonProductomModificar);
        labelButtonProductoModificar.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_panelButtonProductomModificarMouseExited

    private void btnAddMLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMLabelMouseClicked
        dash.setPanelButtonColor2(btnAddMPanel);
        btnAddMLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnAddMLabelMouseClicked

    private void btnAddMLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMLabelMouseEntered
        dash.setPanelButtonColor3(btnAddMPanel);
        btnAddMLabel.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnAddMLabelMouseEntered

    private void btnAddMLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMLabelMouseExited
        dash.setPanelButtonColor2(btnAddMPanel);
        btnAddMLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnAddMLabelMouseExited

    private void btnAddMPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMPanelMouseClicked
        dash.setPanelButtonColor2(btnAddMPanel);
        btnAddMLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnAddMPanelMouseClicked

    private void btnAddMPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMPanelMouseEntered
        dash.setPanelButtonColor3(btnAddMPanel);
        btnAddMLabel.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnAddMPanelMouseEntered

    private void btnAddMPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMPanelMouseExited
        dash.setPanelButtonColor2(btnAddMPanel);
        btnAddMLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnAddMPanelMouseExited

    private void btnVerMLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMLabelMouseClicked
        dash.setPanelButtonColor2(btnVerMPanel);
        btnVerMLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnVerMLabelMouseClicked

    private void btnVerMLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMLabelMouseEntered
        dash.setPanelButtonColor3(btnVerMPanel);
        btnVerMLabel.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnVerMLabelMouseEntered

    private void btnVerMLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMLabelMouseExited
        dash.setPanelButtonColor2(btnVerMPanel);
        btnVerMLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnVerMLabelMouseExited

    private void btnVerMPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMPanelMouseClicked
        dash.setPanelButtonColor2(btnVerMPanel);
        btnVerMLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnVerMPanelMouseClicked

    private void btnVerMPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMPanelMouseEntered
        dash.setPanelButtonColor3(btnVerMPanel);
        btnVerMLabel.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnVerMPanelMouseEntered

    private void btnVerMPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMPanelMouseExited
        dash.setPanelButtonColor2(btnVerMPanel);
        btnVerMLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnVerMPanelMouseExited

    private void btnModMLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModMLabelMouseClicked
        dash.setPanelButtonColor2(btnModMPanel);
        btnModMLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnModMLabelMouseClicked

    private void btnModMLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModMLabelMouseEntered
        dash.setPanelButtonColor3(btnModMPanel);
        btnModMLabel.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnModMLabelMouseEntered

    private void btnModMLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModMLabelMouseExited
        dash.setPanelButtonColor2(btnModMPanel);
        btnModMLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnModMLabelMouseExited

    private void btnModMPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModMPanelMouseClicked
        dash.setPanelButtonColor2(btnModMPanel);
        btnModMLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnModMPanelMouseClicked

    private void btnModMPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModMPanelMouseEntered
        dash.setPanelButtonColor3(btnModMPanel);
        btnModMLabel.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnModMPanelMouseEntered

    private void btnModMPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModMPanelMouseExited
        dash.setPanelButtonColor2(btnModMPanel);
        btnModMLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnModMPanelMouseExited

    private void btnAddUserLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddUserLabelMouseClicked
        dash.setPanelButtonColor2(btnAddUserPanel);
        btnAddUserLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnAddUserLabelMouseClicked

    private void btnAddUserLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddUserLabelMouseEntered
        dash.setPanelButtonColor3(btnAddUserPanel);
        btnAddUserLabel.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnAddUserLabelMouseEntered

    private void btnAddUserLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddUserLabelMouseExited
        dash.setPanelButtonColor2(btnAddUserPanel);
        btnAddUserLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnAddUserLabelMouseExited

    private void btnAddUserPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddUserPanelMouseClicked
        dash.setPanelButtonColor2(btnAddUserPanel);
        btnAddUserLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnAddUserPanelMouseClicked

    private void btnAddUserPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddUserPanelMouseEntered
        dash.setPanelButtonColor3(btnAddUserPanel);
        btnAddUserLabel.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnAddUserPanelMouseEntered

    private void btnAddUserPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddUserPanelMouseExited
        dash.setPanelButtonColor2(btnAddUserPanel);
        btnAddUserLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnAddUserPanelMouseExited

    private void btnVerUserLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerUserLabelMouseClicked
        dash.setPanelButtonColor2(btnVerUserPanel);
        btnVerUserLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnVerUserLabelMouseClicked

    private void btnVerUserLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerUserLabelMouseEntered
        dash.setPanelButtonColor3(btnVerUserPanel);
        btnVerUserLabel.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnVerUserLabelMouseEntered

    private void btnVerUserLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerUserLabelMouseExited
        dash.setPanelButtonColor2(btnVerUserPanel);
        btnVerUserLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnVerUserLabelMouseExited

    private void btnVerUserPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerUserPanelMouseClicked
        dash.setPanelButtonColor2(btnVerUserPanel);
        btnVerUserLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnVerUserPanelMouseClicked

    private void btnVerUserPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerUserPanelMouseEntered
        dash.setPanelButtonColor3(btnVerUserPanel);
        btnVerUserLabel.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnVerUserPanelMouseEntered

    private void btnVerUserPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerUserPanelMouseExited
        dash.setPanelButtonColor2(btnVerUserPanel);
        btnVerUserLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnVerUserPanelMouseExited

    private void btnModUserLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModUserLabelMouseClicked
        dash.setPanelButtonColor2(btnModUserPanel);
        btnModUserLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnModUserLabelMouseClicked

    private void btnModUserLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModUserLabelMouseEntered
        dash.setPanelButtonColor3(btnModUserPanel);
        btnModUserLabel.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnModUserLabelMouseEntered

    private void btnModUserLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModUserLabelMouseExited
        dash.setPanelButtonColor2(btnModUserPanel);
        btnModUserLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnModUserLabelMouseExited

    private void btnModUserPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModUserPanelMouseClicked
        dash.setPanelButtonColor2(btnModUserPanel);
        btnModUserLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnModUserPanelMouseClicked

    private void btnModUserPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModUserPanelMouseEntered
        dash.setPanelButtonColor3(btnModUserPanel);
        btnModUserLabel.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnModUserPanelMouseEntered

    private void btnModUserPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModUserPanelMouseExited
        dash.setPanelButtonColor2(btnModUserPanel);
        btnModUserLabel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnModUserPanelMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnAddMLabel;
    public javax.swing.JPanel btnAddMPanel;
    public javax.swing.JLabel btnAddUserLabel;
    public javax.swing.JPanel btnAddUserPanel;
    public javax.swing.JLabel btnModMLabel;
    public javax.swing.JPanel btnModMPanel;
    public javax.swing.JLabel btnModUserLabel;
    public javax.swing.JPanel btnModUserPanel;
    public javax.swing.JLabel btnVerMLabel;
    public javax.swing.JPanel btnVerMPanel;
    public javax.swing.JLabel btnVerUserLabel;
    public javax.swing.JPanel btnVerUserPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel labelButtonProductoAgregar;
    public javax.swing.JLabel labelButtonProductoModificar;
    public javax.swing.JLabel labelButtonProductoVer;
    public javax.swing.JPanel panelButtonProductoAgregar;
    public javax.swing.JPanel panelButtonProductoVer;
    public javax.swing.JPanel panelButtonProductomModificar;
    // End of variables declaration//GEN-END:variables
}
