/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.awt.Color;

/**
 *
 * @author jesus
 */
public class modificarUsuario extends javax.swing.JPanel {

    public boolean carga = false;
    
    public modificarUsuario() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtBuscarProducto = new design.TextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIDUsuario = new design.TextField();
        jLabel11 = new javax.swing.JLabel();
        txtNombreUsuario = new design.TextField();
        jLabel12 = new javax.swing.JLabel();
        txtCorreo = new design.TextField();
        jLabel13 = new javax.swing.JLabel();
        txtTipoUsuario = new design.Combobox();
        btnAcceptPanel = new javax.swing.JPanel();
        btnAcceptLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIDPersona = new design.TextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtNombresPersona = new design.TextField();
        jLabel17 = new javax.swing.JLabel();
        txtApp = new design.TextField();
        jLabel18 = new javax.swing.JLabel();
        txtApm = new design.TextField();
        calendarFechaPersona = new com.toedter.calendar.JCalendar();
        jLabel19 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1588, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("Editar Usuario");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 35, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 83));

        tabla.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla.setShowGrid(true);
        jScrollPane1.setViewportView(tabla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 770, 800));

        txtBuscarProducto.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtBuscarProducto.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscarProducto.setBorder(null);
        txtBuscarProducto.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtBuscarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBuscarProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBuscarProductoMouseExited(evt);
            }
        });
        txtBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarProductoActionPerformed(evt);
            }
        });
        add(txtBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 770, 30));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setText("Buscar usuario");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel10.setText("ID Usuario");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, -1, -1));

        txtIDUsuario.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtIDUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtIDUsuario.setBorder(null);
        txtIDUsuario.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtIDUsuario.setEnabled(false);
        txtIDUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIDUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtIDUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtIDUsuarioMouseExited(evt);
            }
        });
        txtIDUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDUsuarioActionPerformed(evt);
            }
        });
        add(txtIDUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, 370, 30));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel11.setText("Nombre de usuario");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, -1, -1));

        txtNombreUsuario.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtNombreUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreUsuario.setBorder(null);
        txtNombreUsuario.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtNombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNombreUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNombreUsuarioMouseExited(evt);
            }
        });
        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });
        add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, 750, 30));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel12.setText("Correo");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 260, -1, -1));

        txtCorreo.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreo.setBorder(null);
        txtCorreo.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCorreoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCorreoMouseExited(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, 750, 30));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel13.setText("Clave");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 330, -1, -1));

        txtTipoUsuario.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(txtTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, 750, 35));

        btnAcceptPanel.setBackground(new java.awt.Color(249, 204, 15));
        btnAcceptPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcceptPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAcceptPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcceptPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcceptPanelMouseExited(evt);
            }
        });
        btnAcceptPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAcceptLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnAcceptLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAcceptLabel.setText("GUARDAR");
        btnAcceptLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcceptLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAcceptLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcceptLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcceptLabelMouseExited(evt);
            }
        });
        btnAcceptPanel.add(btnAcceptLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, -1));

        add(btnAcceptPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 880, 750, 40));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel9.setText("Tipo de usuario");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, -1, -1));

        txtIDPersona.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtIDPersona.setForeground(new java.awt.Color(153, 153, 153));
        txtIDPersona.setBorder(null);
        txtIDPersona.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtIDPersona.setEnabled(false);
        txtIDPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIDPersonaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtIDPersonaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtIDPersonaMouseExited(evt);
            }
        });
        txtIDPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDPersonaActionPerformed(evt);
            }
        });
        add(txtIDPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 150, 370, 30));

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel15.setText("ID Persona");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 120, -1, -1));

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel16.setText("Nombres");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, -1, -1));

        txtNombresPersona.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtNombresPersona.setForeground(new java.awt.Color(153, 153, 153));
        txtNombresPersona.setBorder(null);
        txtNombresPersona.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtNombresPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombresPersonaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNombresPersonaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNombresPersonaMouseExited(evt);
            }
        });
        txtNombresPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresPersonaActionPerformed(evt);
            }
        });
        add(txtNombresPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 510, 750, 30));

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel17.setText("Apellido paterno");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 550, -1, -1));

        txtApp.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtApp.setForeground(new java.awt.Color(153, 153, 153));
        txtApp.setBorder(null);
        txtApp.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAppMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAppMouseExited(evt);
            }
        });
        txtApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAppActionPerformed(evt);
            }
        });
        add(txtApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 580, 750, 30));

        jLabel18.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel18.setText("Fecha nacimiento");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 690, -1, -1));

        txtApm.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtApm.setForeground(new java.awt.Color(153, 153, 153));
        txtApm.setBorder(null);
        txtApm.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtApm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtApmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtApmMouseExited(evt);
            }
        });
        txtApm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApmActionPerformed(evt);
            }
        });
        add(txtApm, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 650, 750, 30));
        add(calendarFechaPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 720, 240, 150));

        jLabel19.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel19.setText("Apellido materno");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 620, -1, -1));

        txtClave.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtClave.setForeground(new java.awt.Color(153, 153, 153));
        add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, 750, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProductoMouseClicked

    private void txtBuscarProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarProductoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProductoMouseEntered

    private void txtBuscarProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarProductoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProductoMouseExited

    private void txtBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProductoActionPerformed

    private void txtIDUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDUsuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDUsuarioMouseClicked

    private void txtIDUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDUsuarioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDUsuarioMouseEntered

    private void txtIDUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDUsuarioMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDUsuarioMouseExited

    private void txtIDUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDUsuarioActionPerformed

    private void txtNombreUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreUsuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioMouseClicked

    private void txtNombreUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreUsuarioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioMouseEntered

    private void txtNombreUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreUsuarioMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioMouseExited

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void txtCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoMouseClicked

    private void txtCorreoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoMouseEntered

    private void txtCorreoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoMouseExited

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnAcceptLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptLabelMouseEntered
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(18,5,58));
            btnAcceptLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnAcceptLabelMouseEntered

    private void btnAcceptLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptLabelMouseExited
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(249,204,15));
            btnAcceptLabel.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_btnAcceptLabelMouseExited

    private void btnAcceptPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPanelMouseClicked

    }//GEN-LAST:event_btnAcceptPanelMouseClicked

    private void btnAcceptPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPanelMouseEntered
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(18,5,58));
            btnAcceptLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnAcceptPanelMouseEntered

    private void btnAcceptPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPanelMouseExited
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(249,204,15));
            btnAcceptLabel.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_btnAcceptPanelMouseExited

    private void txtIDPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDPersonaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDPersonaMouseClicked

    private void txtIDPersonaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDPersonaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDPersonaMouseEntered

    private void txtIDPersonaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDPersonaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDPersonaMouseExited

    private void txtIDPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDPersonaActionPerformed

    private void txtNombresPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombresPersonaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresPersonaMouseClicked

    private void txtNombresPersonaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombresPersonaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresPersonaMouseEntered

    private void txtNombresPersonaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombresPersonaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresPersonaMouseExited

    private void txtNombresPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresPersonaActionPerformed

    private void txtAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAppMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppMouseClicked

    private void txtAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAppMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppMouseEntered

    private void txtAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAppMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppMouseExited

    private void txtAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppActionPerformed

    private void txtApmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApmMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApmMouseClicked

    private void txtApmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApmMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApmMouseEntered

    private void txtApmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApmMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApmMouseExited

    private void txtApmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApmActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnAcceptLabel;
    public javax.swing.JPanel btnAcceptPanel;
    public com.toedter.calendar.JCalendar calendarFechaPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabla;
    public javax.swing.JTextField txtApm;
    public javax.swing.JTextField txtApp;
    public javax.swing.JTextField txtBuscarProducto;
    public javax.swing.JPasswordField txtClave;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtIDPersona;
    public javax.swing.JTextField txtIDUsuario;
    public javax.swing.JTextField txtNombreUsuario;
    public javax.swing.JTextField txtNombresPersona;
    public javax.swing.JComboBox<String> txtTipoUsuario;
    // End of variables declaration//GEN-END:variables
}
