/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.awt.Color;

/**
 *
 * @author jesus
 */
public class modificarProducto extends javax.swing.JPanel {

    public boolean carga = false;
    
    public modificarProducto() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtBuscarProducto = new design.TextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIDProducto = new design.TextField();
        jLabel11 = new javax.swing.JLabel();
        txtCodigoProducto = new design.TextField();
        jLabel12 = new javax.swing.JLabel();
        txtNombreProducto = new design.TextField();
        jLabel13 = new javax.swing.JLabel();
        txtPrecioProducto = new design.TextField();
        jLabel14 = new javax.swing.JLabel();
        txtCostoProducto = new design.TextField();
        comboMarca = new design.Combobox();
        btnAcceptPanel = new javax.swing.JPanel();
        btnAcceptLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        checkVisibleProducto = new design.JCheckBoxCustom();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1588, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("Editar Producto");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 35, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 83));

        tabla.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla.setShowGrid(true);
        jScrollPane1.setViewportView(tabla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 770, 800));

        txtBuscarProducto.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtBuscarProducto.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscarProducto.setBorder(null);
        txtBuscarProducto.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtBuscarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBuscarProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBuscarProductoMouseExited(evt);
            }
        });
        txtBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarProductoActionPerformed(evt);
            }
        });
        add(txtBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 770, 30));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setText("Buscar producto");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel10.setText("ID");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, -1, -1));

        txtIDProducto.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtIDProducto.setForeground(new java.awt.Color(153, 153, 153));
        txtIDProducto.setBorder(null);
        txtIDProducto.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtIDProducto.setEnabled(false);
        txtIDProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIDProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtIDProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtIDProductoMouseExited(evt);
            }
        });
        txtIDProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDProductoActionPerformed(evt);
            }
        });
        add(txtIDProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, 750, 30));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel11.setText("Codigo");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, -1, -1));

        txtCodigoProducto.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtCodigoProducto.setForeground(new java.awt.Color(153, 153, 153));
        txtCodigoProducto.setBorder(null);
        txtCodigoProducto.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtCodigoProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCodigoProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCodigoProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCodigoProductoMouseExited(evt);
            }
        });
        txtCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProductoActionPerformed(evt);
            }
        });
        add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, 750, 30));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel12.setText("Nombre");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 260, -1, -1));

        txtNombreProducto.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtNombreProducto.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreProducto.setBorder(null);
        txtNombreProducto.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtNombreProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNombreProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNombreProductoMouseExited(evt);
            }
        });
        txtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoActionPerformed(evt);
            }
        });
        add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, 750, 30));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel13.setText("Precio");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 330, -1, -1));

        txtPrecioProducto.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtPrecioProducto.setForeground(new java.awt.Color(153, 153, 153));
        txtPrecioProducto.setBorder(null);
        txtPrecioProducto.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtPrecioProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPrecioProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPrecioProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPrecioProductoMouseExited(evt);
            }
        });
        txtPrecioProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioProductoActionPerformed(evt);
            }
        });
        add(txtPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, 750, 30));

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel14.setText("Costo");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, -1, -1));

        txtCostoProducto.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtCostoProducto.setForeground(new java.awt.Color(153, 153, 153));
        txtCostoProducto.setBorder(null);
        txtCostoProducto.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtCostoProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCostoProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCostoProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCostoProductoMouseExited(evt);
            }
        });
        txtCostoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoProductoActionPerformed(evt);
            }
        });
        add(txtCostoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, 750, 30));

        comboMarca.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        comboMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 500, 750, 35));

        btnAcceptPanel.setBackground(new java.awt.Color(249, 204, 15));
        btnAcceptPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcceptPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAcceptPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcceptPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcceptPanelMouseExited(evt);
            }
        });
        btnAcceptPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAcceptLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnAcceptLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAcceptLabel.setText("GUARDAR");
        btnAcceptLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcceptLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAcceptLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcceptLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcceptLabelMouseExited(evt);
            }
        });
        btnAcceptPanel.add(btnAcceptLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, -1));

        add(btnAcceptPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 580, 750, 40));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel8.setText("  Visible");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 550, 80, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel9.setText("Marca del producto");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 470, -1, -1));

        checkVisibleProducto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(checkVisibleProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 550, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProductoMouseClicked

    private void txtBuscarProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarProductoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProductoMouseEntered

    private void txtBuscarProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarProductoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProductoMouseExited

    private void txtBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProductoActionPerformed

    private void txtIDProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDProductoMouseClicked

    private void txtIDProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDProductoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDProductoMouseEntered

    private void txtIDProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDProductoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDProductoMouseExited

    private void txtIDProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDProductoActionPerformed

    private void txtCodigoProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProductoMouseClicked

    private void txtCodigoProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoProductoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProductoMouseEntered

    private void txtCodigoProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoProductoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProductoMouseExited

    private void txtCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProductoActionPerformed

    private void txtNombreProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoMouseClicked

    private void txtNombreProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreProductoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoMouseEntered

    private void txtNombreProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreProductoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoMouseExited

    private void txtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoActionPerformed

    private void txtPrecioProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrecioProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioProductoMouseClicked

    private void txtPrecioProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrecioProductoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioProductoMouseEntered

    private void txtPrecioProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrecioProductoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioProductoMouseExited

    private void txtPrecioProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioProductoActionPerformed

    private void txtCostoProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCostoProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoProductoMouseClicked

    private void txtCostoProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCostoProductoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoProductoMouseEntered

    private void txtCostoProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCostoProductoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoProductoMouseExited

    private void txtCostoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoProductoActionPerformed

    private void btnAcceptLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptLabelMouseEntered
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(18,5,58));
            btnAcceptLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnAcceptLabelMouseEntered

    private void btnAcceptLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptLabelMouseExited
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(249,204,15));
            btnAcceptLabel.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_btnAcceptLabelMouseExited

    private void btnAcceptPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPanelMouseClicked

    }//GEN-LAST:event_btnAcceptPanelMouseClicked

    private void btnAcceptPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPanelMouseEntered
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(18,5,58));
            btnAcceptLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnAcceptPanelMouseEntered

    private void btnAcceptPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPanelMouseExited
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(249,204,15));
            btnAcceptLabel.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_btnAcceptPanelMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnAcceptLabel;
    public javax.swing.JPanel btnAcceptPanel;
    public javax.swing.JCheckBox checkVisibleProducto;
    public javax.swing.JComboBox<String> comboMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabla;
    public javax.swing.JTextField txtBuscarProducto;
    public javax.swing.JTextField txtCodigoProducto;
    public javax.swing.JTextField txtCostoProducto;
    public javax.swing.JTextField txtIDProducto;
    public javax.swing.JTextField txtNombreProducto;
    public javax.swing.JTextField txtPrecioProducto;
    // End of variables declaration//GEN-END:variables
}
