/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.awt.Color;

/**
 *
 * @author jesus
 */
public class modificarMarca extends javax.swing.JPanel {

    public boolean carga = false;
    
    public modificarMarca() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtBuscarProducto = new design.TextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIDMarca = new design.TextField();
        jLabel11 = new javax.swing.JLabel();
        txtNombreMarca = new design.TextField();
        btnAcceptPanel = new javax.swing.JPanel();
        btnAcceptLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1588, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("Editar Marca");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 35, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 83));

        tabla.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla.setShowGrid(true);
        jScrollPane1.setViewportView(tabla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 770, 800));

        txtBuscarProducto.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtBuscarProducto.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscarProducto.setBorder(null);
        txtBuscarProducto.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtBuscarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBuscarProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBuscarProductoMouseExited(evt);
            }
        });
        txtBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarProductoActionPerformed(evt);
            }
        });
        add(txtBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 770, 30));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setText("Buscar marca");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel10.setText("ID");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, -1, -1));

        txtIDMarca.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtIDMarca.setForeground(new java.awt.Color(153, 153, 153));
        txtIDMarca.setBorder(null);
        txtIDMarca.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtIDMarca.setEnabled(false);
        txtIDMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIDMarcaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtIDMarcaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtIDMarcaMouseExited(evt);
            }
        });
        txtIDMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDMarcaActionPerformed(evt);
            }
        });
        add(txtIDMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, 750, 30));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel11.setText("Nombre");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, -1, -1));

        txtNombreMarca.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtNombreMarca.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreMarca.setBorder(null);
        txtNombreMarca.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtNombreMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMarcaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNombreMarcaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNombreMarcaMouseExited(evt);
            }
        });
        txtNombreMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreMarcaActionPerformed(evt);
            }
        });
        add(txtNombreMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, 750, 30));

        btnAcceptPanel.setBackground(new java.awt.Color(249, 204, 15));
        btnAcceptPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcceptPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAcceptPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcceptPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcceptPanelMouseExited(evt);
            }
        });
        btnAcceptPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAcceptLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnAcceptLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAcceptLabel.setText("GUARDAR");
        btnAcceptLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcceptLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAcceptLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcceptLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcceptLabelMouseExited(evt);
            }
        });
        btnAcceptPanel.add(btnAcceptLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, -1));

        add(btnAcceptPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 280, 750, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProductoMouseClicked

    private void txtBuscarProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarProductoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProductoMouseEntered

    private void txtBuscarProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarProductoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProductoMouseExited

    private void txtBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProductoActionPerformed

    private void txtIDMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDMarcaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDMarcaMouseClicked

    private void txtIDMarcaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDMarcaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDMarcaMouseEntered

    private void txtIDMarcaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDMarcaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDMarcaMouseExited

    private void txtIDMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDMarcaActionPerformed

    private void txtNombreMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMarcaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMarcaMouseClicked

    private void txtNombreMarcaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMarcaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMarcaMouseEntered

    private void txtNombreMarcaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMarcaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMarcaMouseExited

    private void txtNombreMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMarcaActionPerformed

    private void btnAcceptLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptLabelMouseEntered
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(18,5,58));
            btnAcceptLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnAcceptLabelMouseEntered

    private void btnAcceptLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptLabelMouseExited
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(249,204,15));
            btnAcceptLabel.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_btnAcceptLabelMouseExited

    private void btnAcceptPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPanelMouseClicked

    }//GEN-LAST:event_btnAcceptPanelMouseClicked

    private void btnAcceptPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPanelMouseEntered
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(18,5,58));
            btnAcceptLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnAcceptPanelMouseEntered

    private void btnAcceptPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPanelMouseExited
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(249,204,15));
            btnAcceptLabel.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_btnAcceptPanelMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnAcceptLabel;
    public javax.swing.JPanel btnAcceptPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabla;
    public javax.swing.JTextField txtBuscarProducto;
    public javax.swing.JTextField txtIDMarca;
    public javax.swing.JTextField txtNombreMarca;
    // End of variables declaration//GEN-END:variables
}
