/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.awt.Color;

/**
 *
 * @author jesus
 */
public class nuevaVenta extends javax.swing.JPanel {

    public boolean carga = false;
    
    public nuevaVenta() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEliminarArticulo = new javax.swing.JPanel();
        btnNoDelPananel = new javax.swing.JPanel();
        btnNoDelLabel = new javax.swing.JLabel();
        btnDelPanel = new javax.swing.JPanel();
        btnDelLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelFinalizar = new javax.swing.JPanel();
        btnNoFinPanel = new javax.swing.JPanel();
        btnNoFinLabel = new javax.swing.JLabel();
        btnFinPanel = new javax.swing.JPanel();
        btnFinLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelAgregarArticulo = new javax.swing.JPanel();
        btnNoAddPanel = new javax.swing.JPanel();
        btnNoAddLabel = new javax.swing.JLabel();
        btnAddPanel = new javax.swing.JPanel();
        btnAddLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        txtBuscarProducto = new design.TextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCarrito = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtIDCarrito = new design.TextField();
        jLabel12 = new javax.swing.JLabel();
        txtNombreProducto = new design.TextField();
        jLabel13 = new javax.swing.JLabel();
        txtPrecioProducto = new design.TextField();
        jLabel14 = new javax.swing.JLabel();
        txtPago = new design.TextField();
        btnEliminarPanel = new javax.swing.JPanel();
        btnEliminarLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCodigoProducto = new design.TextField();
        btnAcceptPanel = new javax.swing.JPanel();
        btnAcceptLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTotalPro = new javax.swing.JLabel();
        comboMetodos = new design.Combobox();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCantidad = new design.TextField();
        jLabel18 = new javax.swing.JLabel();
        txtCambio = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1588, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEliminarArticulo.setBackground(new java.awt.Color(255, 255, 255));
        panelEliminarArticulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 5, 58)));
        panelEliminarArticulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNoDelPananel.setBackground(new java.awt.Color(255, 51, 51));
        btnNoDelPananel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNoDelPananel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNoDelPananelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNoDelPananelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNoDelPananelMouseExited(evt);
            }
        });
        btnNoDelPananel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNoDelLabel.setBackground(new java.awt.Color(255, 0, 0));
        btnNoDelLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnNoDelLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnNoDelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNoDelLabel.setText("NO");
        btnNoDelLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNoDelLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNoDelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNoDelLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNoDelLabelMouseExited(evt);
            }
        });
        btnNoDelPananel.add(btnNoDelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, -1));

        panelEliminarArticulo.add(btnNoDelPananel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 360, 40));

        btnDelPanel.setBackground(new java.awt.Color(249, 204, 15));
        btnDelPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDelPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDelPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDelPanelMouseExited(evt);
            }
        });
        btnDelPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDelLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnDelLabel.setForeground(new java.awt.Color(0, 0, 0));
        btnDelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDelLabel.setText("SI");
        btnDelLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDelLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDelLabelMouseExited(evt);
            }
        });
        btnDelPanel.add(btnDelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, -1));

        panelEliminarArticulo.add(btnDelPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 360, 40));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Quieres eliminar el articulo del carrito?");
        panelEliminarArticulo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, 40));

        add(panelEliminarArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 750, 120));

        panelFinalizar.setBackground(new java.awt.Color(255, 255, 255));
        panelFinalizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 5, 58)));
        panelFinalizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNoFinPanel.setBackground(new java.awt.Color(255, 51, 51));
        btnNoFinPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNoFinPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNoFinPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNoFinPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNoFinPanelMouseExited(evt);
            }
        });
        btnNoFinPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNoFinLabel.setBackground(new java.awt.Color(255, 0, 0));
        btnNoFinLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnNoFinLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnNoFinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNoFinLabel.setText("NO");
        btnNoFinLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNoFinLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNoFinLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNoFinLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNoFinLabelMouseExited(evt);
            }
        });
        btnNoFinPanel.add(btnNoFinLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, -1));

        panelFinalizar.add(btnNoFinPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 360, 40));

        btnFinPanel.setBackground(new java.awt.Color(249, 204, 15));
        btnFinPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFinPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFinPanelMouseExited(evt);
            }
        });
        btnFinPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFinLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnFinLabel.setForeground(new java.awt.Color(0, 0, 0));
        btnFinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnFinLabel.setText("SI");
        btnFinLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFinLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFinLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFinLabelMouseExited(evt);
            }
        });
        btnFinPanel.add(btnFinLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, -1));

        panelFinalizar.add(btnFinPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 360, 40));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Quieres finalizar la venta?");
        panelFinalizar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, 40));

        add(panelFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 750, 120));

        panelAgregarArticulo.setBackground(new java.awt.Color(255, 255, 255));
        panelAgregarArticulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 5, 58)));
        panelAgregarArticulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNoAddPanel.setBackground(new java.awt.Color(255, 51, 51));
        btnNoAddPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNoAddPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNoAddPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNoAddPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNoAddPanelMouseExited(evt);
            }
        });
        btnNoAddPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNoAddLabel.setBackground(new java.awt.Color(255, 0, 0));
        btnNoAddLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnNoAddLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnNoAddLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNoAddLabel.setText("NO AGREGAR");
        btnNoAddLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNoAddLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNoAddLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNoAddLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNoAddLabelMouseExited(evt);
            }
        });
        btnNoAddPanel.add(btnNoAddLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, -1));

        panelAgregarArticulo.add(btnNoAddPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 360, 40));

        btnAddPanel.setBackground(new java.awt.Color(249, 204, 15));
        btnAddPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddPanelMouseExited(evt);
            }
        });
        btnAddPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnAddLabel.setForeground(new java.awt.Color(0, 0, 0));
        btnAddLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddLabel.setText("SI AGREGAR");
        btnAddLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddLabelMouseExited(evt);
            }
        });
        btnAddPanel.add(btnAddLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, -1));

        panelAgregarArticulo.add(btnAddPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 360, 40));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Quieres agregar el articulo al carrito?");
        panelAgregarArticulo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, 40));

        add(panelAgregarArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 750, 120));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("Punto de venta");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 35, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 83));

        tablaProductos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaProductos.setShowGrid(true);
        jScrollPane1.setViewportView(tablaProductos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 770, 350));

        txtBuscarProducto.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtBuscarProducto.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscarProducto.setBorder(null);
        txtBuscarProducto.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtBuscarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBuscarProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBuscarProductoMouseExited(evt);
            }
        });
        txtBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarProductoActionPerformed(evt);
            }
        });
        add(txtBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 770, 30));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setText("Carrito");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel8.setText("Buscar producto");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        tablaCarrito.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tablaCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaCarrito.setShowGrid(true);
        jScrollPane2.setViewportView(tablaCarrito);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 770, 400));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel11.setText("ID Carrito");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, -1, -1));

        txtIDCarrito.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtIDCarrito.setForeground(new java.awt.Color(153, 153, 153));
        txtIDCarrito.setBorder(null);
        txtIDCarrito.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtIDCarrito.setEnabled(false);
        txtIDCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIDCarritoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtIDCarritoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtIDCarritoMouseExited(evt);
            }
        });
        txtIDCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDCarritoActionPerformed(evt);
            }
        });
        add(txtIDCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, 370, 30));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel12.setText("Articulo");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, -1, -1));

        txtNombreProducto.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtNombreProducto.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreProducto.setBorder(null);
        txtNombreProducto.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtNombreProducto.setEnabled(false);
        txtNombreProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNombreProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNombreProductoMouseExited(evt);
            }
        });
        txtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoActionPerformed(evt);
            }
        });
        add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, 750, 30));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel13.setText("Precio");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 260, -1, -1));

        txtPrecioProducto.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtPrecioProducto.setForeground(new java.awt.Color(153, 153, 153));
        txtPrecioProducto.setBorder(null);
        txtPrecioProducto.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtPrecioProducto.setEnabled(false);
        txtPrecioProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPrecioProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPrecioProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPrecioProductoMouseExited(evt);
            }
        });
        txtPrecioProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioProductoActionPerformed(evt);
            }
        });
        add(txtPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, 750, 30));

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Total a pagar:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(822, 620, 120, -1));

        txtPago.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtPago.setForeground(new java.awt.Color(153, 153, 153));
        txtPago.setBorder(null);
        txtPago.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPagoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPagoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPagoMouseExited(evt);
            }
        });
        txtPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagoActionPerformed(evt);
            }
        });
        txtPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPagoKeyReleased(evt);
            }
        });
        add(txtPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 790, 750, 30));

        btnEliminarPanel.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminarPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarPanelMouseExited(evt);
            }
        });
        btnEliminarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnEliminarLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEliminarLabel.setText("ELIMINAR DEL CARRITO");
        btnEliminarLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarLabelMouseExited(evt);
            }
        });
        btnEliminarPanel.add(btnEliminarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, -1));

        add(btnEliminarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 500, 750, 40));

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel15.setText("Cantidad");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, -1, -1));

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel16.setText("Codigo");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 120, -1, -1));

        txtCodigoProducto.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtCodigoProducto.setForeground(new java.awt.Color(153, 153, 153));
        txtCodigoProducto.setBorder(null);
        txtCodigoProducto.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtCodigoProducto.setEnabled(false);
        txtCodigoProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCodigoProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCodigoProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCodigoProductoMouseExited(evt);
            }
        });
        txtCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProductoActionPerformed(evt);
            }
        });
        add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 150, 370, 30));

        btnAcceptPanel.setBackground(new java.awt.Color(249, 204, 15));
        btnAcceptPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcceptPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAcceptPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcceptPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcceptPanelMouseExited(evt);
            }
        });
        btnAcceptPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAcceptLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnAcceptLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAcceptLabel.setText("FINALIZAR VENTA");
        btnAcceptLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcceptLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAcceptLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcceptLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcceptLabelMouseExited(evt);
            }
        });
        btnAcceptPanel.add(btnAcceptLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, -1));

        add(btnAcceptPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 940, 750, 40));

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel17.setText("Editar carrito");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 390, -1, -1));

        txtTotal.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTotal.setText("$0");
        add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 620, 60, -1));

        jLabel19.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Total de productos:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 590, 170, -1));

        txtTotalPro.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtTotalPro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTotalPro.setText("0");
        add(txtTotalPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 590, 60, -1));

        comboMetodos.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        comboMetodos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMetodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMetodosActionPerformed(evt);
            }
        });
        add(comboMetodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 710, 750, 35));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setText("Por donde pago?");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 680, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel9.setText("Con cuanto pago?");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 760, -1, -1));

        txtCantidad.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(153, 153, 153));
        txtCantidad.setBorder(null);
        txtCantidad.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCantidadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCantidadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCantidadMouseExited(evt);
            }
        });
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadKeyReleased(evt);
            }
        });
        add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 450, 750, 30));

        jLabel18.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Cambio:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 850, 70, -1));

        txtCambio.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCambio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtCambio.setText("$0");
        add(txtCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 850, 60, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProductoMouseClicked

    private void txtBuscarProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarProductoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProductoMouseEntered

    private void txtBuscarProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarProductoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProductoMouseExited

    private void txtBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProductoActionPerformed

    private void txtIDCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDCarritoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDCarritoMouseClicked

    private void txtIDCarritoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDCarritoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDCarritoMouseEntered

    private void txtIDCarritoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDCarritoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDCarritoMouseExited

    private void txtIDCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDCarritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDCarritoActionPerformed

    private void txtNombreProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoMouseClicked

    private void txtNombreProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreProductoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoMouseEntered

    private void txtNombreProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreProductoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoMouseExited

    private void txtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoActionPerformed

    private void txtPrecioProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrecioProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioProductoMouseClicked

    private void txtPrecioProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrecioProductoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioProductoMouseEntered

    private void txtPrecioProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrecioProductoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioProductoMouseExited

    private void txtPrecioProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioProductoActionPerformed

    private void txtPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPagoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagoMouseClicked

    private void txtPagoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPagoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagoMouseEntered

    private void txtPagoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPagoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagoMouseExited

    private void txtPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagoActionPerformed

    private void btnEliminarLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarLabelMouseEntered
        if(carga == false){
            btnEliminarPanel.setBackground(new Color(255,0,0));
            btnEliminarLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnEliminarLabelMouseEntered

    private void btnEliminarLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarLabelMouseExited
        if(carga == false){            
            btnEliminarPanel.setBackground(new Color(255,51,51));
            btnEliminarLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnEliminarLabelMouseExited

    private void btnEliminarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarPanelMouseClicked

    }//GEN-LAST:event_btnEliminarPanelMouseClicked

    private void btnEliminarPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarPanelMouseEntered
        if(carga == false){
            btnEliminarPanel.setBackground(new Color(255,0,0));
            btnEliminarLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnEliminarPanelMouseEntered

    private void btnEliminarPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarPanelMouseExited
        if(carga == false){            
            btnEliminarPanel.setBackground(new Color(255,51,51));
            btnEliminarLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnEliminarPanelMouseExited

    private void txtCodigoProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProductoMouseClicked

    private void txtCodigoProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoProductoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProductoMouseEntered

    private void txtCodigoProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoProductoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProductoMouseExited

    private void txtCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProductoActionPerformed

    private void btnAcceptLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptLabelMouseEntered
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(18,5,58));
            btnAcceptLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnAcceptLabelMouseEntered

    private void btnAcceptLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptLabelMouseExited
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(249,204,15));
            btnAcceptLabel.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_btnAcceptLabelMouseExited

    private void btnAcceptPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAcceptPanelMouseClicked

    private void btnAcceptPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPanelMouseEntered
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(18,5,58));
            btnAcceptLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnAcceptPanelMouseEntered

    private void btnAcceptPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPanelMouseExited
        if(carga == false){
            btnAcceptPanel.setBackground(new Color(249,204,15));
            btnAcceptLabel.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_btnAcceptPanelMouseExited

    private void btnNoAddLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoAddLabelMouseEntered
        if(carga == false){
            btnNoAddPanel.setBackground(new Color(255,0,0));
            btnNoAddLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnNoAddLabelMouseEntered

    private void btnNoAddLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoAddLabelMouseExited
        if(carga == false){            
            btnNoAddPanel.setBackground(new Color(255,51,51));
            btnNoAddLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnNoAddLabelMouseExited

    private void btnNoAddPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoAddPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNoAddPanelMouseClicked

    private void btnNoAddPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoAddPanelMouseEntered
        if(carga == false){
            btnNoAddPanel.setBackground(new Color(255,0,0));
            btnNoAddLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnNoAddPanelMouseEntered

    private void btnNoAddPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoAddPanelMouseExited
        if(carga == false){            
            btnNoAddPanel.setBackground(new Color(255,51,51));
            btnNoAddLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnNoAddPanelMouseExited

    private void btnAddLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddLabelMouseEntered
        if(carga == false){
            btnAddPanel.setBackground(new Color(18,5,58));
            btnAddLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnAddLabelMouseEntered

    private void btnAddLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddLabelMouseExited
        if(carga == false){
            btnAddPanel.setBackground(new Color(249,204,15));
            btnAddLabel.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_btnAddLabelMouseExited

    private void btnAddPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddPanelMouseClicked

    private void btnAddPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPanelMouseEntered
        if(carga == false){
            btnAddPanel.setBackground(new Color(18,5,58));
            btnAddLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnAddPanelMouseEntered

    private void btnAddPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPanelMouseExited
        if(carga == false){
            btnAddPanel.setBackground(new Color(249,204,15));
            btnAddLabel.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_btnAddPanelMouseExited

    private void btnNoDelLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoDelLabelMouseEntered
        if(carga == false){
            btnNoDelPananel.setBackground(new Color(255,0,0));
            btnNoDelLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnNoDelLabelMouseEntered

    private void btnNoDelLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoDelLabelMouseExited
        if(carga == false){            
            btnNoDelPananel.setBackground(new Color(255,51,51));
            btnNoDelLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnNoDelLabelMouseExited

    private void btnNoDelPananelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoDelPananelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNoDelPananelMouseClicked

    private void btnNoDelPananelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoDelPananelMouseEntered
       if(carga == false){
            btnNoDelPananel.setBackground(new Color(255,0,0));
            btnNoDelLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnNoDelPananelMouseEntered

    private void btnNoDelPananelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoDelPananelMouseExited
        if(carga == false){            
            btnNoDelPananel.setBackground(new Color(255,51,51));
            btnNoDelLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnNoDelPananelMouseExited

    private void btnDelLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelLabelMouseEntered
        if(carga == false){
            btnDelPanel.setBackground(new Color(18,5,58));
            btnDelLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnDelLabelMouseEntered

    private void btnDelLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelLabelMouseExited
        if(carga == false){
            btnDelPanel.setBackground(new Color(249,204,15));
            btnDelLabel.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_btnDelLabelMouseExited

    private void btnDelPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelPanelMouseClicked

    private void btnDelPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelPanelMouseEntered
        if(carga == false){
            btnDelPanel.setBackground(new Color(18,5,58));
            btnDelLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnDelPanelMouseEntered

    private void btnDelPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelPanelMouseExited
        if(carga == false){
            btnDelPanel.setBackground(new Color(249,204,15));
            btnDelLabel.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_btnDelPanelMouseExited

    private void txtPagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagoKeyReleased

    private void comboMetodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMetodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMetodosActionPerformed

    private void txtCantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCantidadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadMouseClicked

    private void txtCantidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCantidadMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadMouseEntered

    private void txtCantidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCantidadMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadMouseExited

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadKeyReleased

    private void btnNoFinLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoFinLabelMouseEntered
        if(carga == false){
            btnNoFinPanel.setBackground(new Color(255,0,0));
            btnNoFinLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnNoFinLabelMouseEntered

    private void btnNoFinLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoFinLabelMouseExited
        if(carga == false){            
            btnNoFinPanel.setBackground(new Color(255,51,51));
            btnNoFinLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnNoFinLabelMouseExited

    private void btnNoFinPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoFinPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNoFinPanelMouseClicked

    private void btnNoFinPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoFinPanelMouseEntered
        if(carga == false){
            btnNoFinPanel.setBackground(new Color(255,0,0));
            btnNoFinLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnNoFinPanelMouseEntered

    private void btnNoFinPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoFinPanelMouseExited
        if(carga == false){            
            btnNoFinPanel.setBackground(new Color(255,51,51));
            btnNoFinLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnNoFinPanelMouseExited

    private void btnFinLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinLabelMouseEntered
        if(carga == false){
            btnFinPanel.setBackground(new Color(18,5,58));
            btnFinLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnFinLabelMouseEntered

    private void btnFinLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinLabelMouseExited
        if(carga == false){
            btnFinPanel.setBackground(new Color(249,204,15));
            btnFinLabel.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_btnFinLabelMouseExited

    private void btnFinPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinPanelMouseClicked

    private void btnFinPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinPanelMouseEntered
        if(carga == false){
            btnFinPanel.setBackground(new Color(18,5,58));
            btnFinLabel.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btnFinPanelMouseEntered

    private void btnFinPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinPanelMouseExited
        if(carga == false){
            btnFinPanel.setBackground(new Color(249,204,15));
            btnFinLabel.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_btnFinPanelMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnAcceptLabel;
    public javax.swing.JPanel btnAcceptPanel;
    public javax.swing.JLabel btnAddLabel;
    public javax.swing.JPanel btnAddPanel;
    public javax.swing.JLabel btnDelLabel;
    public javax.swing.JPanel btnDelPanel;
    public javax.swing.JLabel btnEliminarLabel;
    public javax.swing.JPanel btnEliminarPanel;
    public javax.swing.JLabel btnFinLabel;
    public javax.swing.JPanel btnFinPanel;
    public javax.swing.JLabel btnNoAddLabel;
    public javax.swing.JPanel btnNoAddPanel;
    public javax.swing.JLabel btnNoDelLabel;
    public javax.swing.JPanel btnNoDelPananel;
    public javax.swing.JLabel btnNoFinLabel;
    public javax.swing.JPanel btnNoFinPanel;
    public javax.swing.JComboBox<String> comboMetodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JPanel panelAgregarArticulo;
    public javax.swing.JPanel panelEliminarArticulo;
    public javax.swing.JPanel panelFinalizar;
    public javax.swing.JTable tablaCarrito;
    public javax.swing.JTable tablaProductos;
    public javax.swing.JTextField txtBuscarProducto;
    public javax.swing.JLabel txtCambio;
    public javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtCodigoProducto;
    public javax.swing.JTextField txtIDCarrito;
    public javax.swing.JTextField txtNombreProducto;
    public javax.swing.JTextField txtPago;
    public javax.swing.JTextField txtPrecioProducto;
    public javax.swing.JLabel txtTotal;
    public javax.swing.JLabel txtTotalPro;
    // End of variables declaration//GEN-END:variables
}
